// Create a User
POST http://localhost:5000/users
Content-Type: application/json

{
"name": "Ajik",
"email": "Ajik@gmail.com",
"password": "123456",
"confPassword": "123456",
"role": "admin"
}

###
// Get All Users
GET http://localhost:5000/users

###
// Get Single Users
GET http://localhost:5000/users/afe4e77a-5c75-4257-b8f7-871367cb283f

###
// Updating a Users
PATCH http://localhost:5000/users/a3fd3e63-3753-4f59-b1b3-d879e22128b7
Content-Type: application/json

{
"name": "John Updated",
"email": "John@gmail.com",
"password": "",
"confPassword": "",
"role": "user"
}

###
// Delete User
DELETE http://localhost:5000/users/cd2a7b48-a8ec-457e-a16b-9784b3823689

###
// Logging in a User
POST http://localhost:5000/login
Content-Type: application/json

{
"email": "ardivan@gmail.com",
"password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
"email": "Ajik@gmail.com",
"password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
"email": "John@gmail.com",
"password": "123456"
}

###
// Get Me
GET http://localhost:5000/me
###
//LogOut User
DELETE http://localhost:5000/logout


###
// Get All Message
GET http://localhost:5000/chatchannels


// Send Message
###
POST http://localhost:5000/chats
Content-Type: application/json

{
"sender": "ardivan",
"receiver": "John Doe",
"message": "Hello, how can I assist you?"
}


###
// Create Repair Shop
POST http://localhost:5000/repairshops
Content-Type: multipart/form-data

image=@/path/to/your/image.jpg
name=Example Repair Shop
address=123 Main Street
phone_number=1234567890
latitude=10.123456
longitude=20.654321


###
// Get repairshop
GET http://localhost:5000/repairshops


###
// Get repairshop by Id
GET http://localhost:5000/repairshops/2
###
// Update repairshop
PATCH http://localhost:5000/repairshops/2
Content-Type: application/json

{
"name": "Nama Repair Shop Baru"
}


###
// Delete repairshop
DELETE http://localhost:5000/repairshops/2
###
// Create Operational Schedule
POST http://localhost:5000/operationalschedules
Content-Type: application/json

{
"repairShopId": 2,
"day": "Monday",
"openingTime": "09:00:00",
"closingTime": "18:00:00",
"status": "open"
}


###
GET http://localhost:5000/operationalschedules/2


###
PATCH http://localhost:5000/operationalschedules/2
Content-Type: application/json

{
"repairShopId": 2,
"day": "Monday",
"openingTime": "10:00:00",
"closingTime": "19:00:00",
"status": "open"
}
